{
  "openapi": "3.0.0",
  "info": {
    "title": "Courses",
    "version": "1.0",
    "description": "Courses APis"
  },
  "servers": [
    {
      "url": "https://ertiqa.svod.app/api/courses"
    }
  ],
  "paths": {
    "/all": {
      "post": {
        "summary": "Get All Courses",
        "operationId": "post-all",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Example": {
                    "value": {
                      "status": "Action Completed",
                      "message": "تم جلب الدورات التدريبية",
                      "data": {
                        "current_page": 1,
                        "data": [
                          {
                            "courseID": 43,
                            "title": "📢الدورة التاسعة لورشة عمل مراجعة الأمراض المعدية لدى الأطفال",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20201021210914.jpeg",
                            "coverH": 1280,
                            "coverW": 906,
                            "publishDate": "2020-10-21 21:54:30",
                            "publisheWrit": "اليوم",
                            "viewCount": 0,
                            "description": null,
                            "registrationState": "Open"
                          },
                          {
                            "courseID": 33,
                            "title": "عنوان الدورة التدريبة",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200929193120.jpeg",
                            "coverH": 750,
                            "coverW": 750,
                            "publishDate": "2020-09-29 19:32:22",
                            "publisheWrit": "خلال هذا الشهر",
                            "viewCount": 71,
                            "description": null,
                            "registrationState": "close"
                          },
                          {
                            "courseID": 28,
                            "title": "دورة تشخيص و علاج مشاكل مفصل القدم",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200925060922.jpeg",
                            "coverH": 1280,
                            "coverW": 839,
                            "publishDate": "2020-09-25 07:00:56",
                            "publisheWrit": "خلال هذا الشهر",
                            "viewCount": 79,
                            "description": null,
                            "registrationState": "not Open"
                          },
                          {
                            "courseID": 22,
                            "title": "ملتقى متطوع بعلمي",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200921170711.jpeg",
                            "coverH": 198,
                            "coverW": 214,
                            "publishDate": "2020-09-24 18:53:35",
                            "publisheWrit": "خلال هذا الشهر",
                            "viewCount": 15,
                            "description": null,
                            "registrationState": "close"
                          },
                          {
                            "courseID": 27,
                            "title": "📢 صحتك بعد الأربعين   🏢أون لاين",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200923140325.jpeg",
                            "coverH": 1280,
                            "coverW": 904,
                            "publishDate": "2020-09-24 18:53:25",
                            "publisheWrit": "خلال هذا الشهر",
                            "viewCount": 34,
                            "description": null,
                            "registrationState": "close"
                          },
                          {
                            "courseID": 26,
                            "title": "📢 دبلوم إدارة المستشفيات والمراكز الصحية 💻 اون لاين",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200923112633.jpeg",
                            "coverH": 198,
                            "coverW": 214,
                            "publishDate": "2020-09-23 11:33:31",
                            "publisheWrit": "قبل شهر",
                            "viewCount": 8,
                            "description": null,
                            "registrationState": "close"
                          },
                          {
                            "courseID": 25,
                            "title": "Certified Professional in Healthcare Management ( CPHMG ) Course",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200923111413.jpeg",
                            "coverH": 198,
                            "coverW": 214,
                            "publishDate": "2020-09-23 11:21:29",
                            "publisheWrit": "قبل شهر",
                            "viewCount": 5,
                            "description": "‏AMERICAN INSTITUTE FOR HEALTHCARE MANAGEMENT , (AMIHM’s)",
                            "registrationState": "close"
                          },
                          {
                            "courseID": 24,
                            "title": "📢 ملتقى متطوع بعلمي .  🏢 اون لاين",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200923110203.jpg",
                            "coverH": 198,
                            "coverW": 214,
                            "publishDate": "2020-09-23 11:08:04",
                            "publisheWrit": "قبل شهر",
                            "viewCount": 6,
                            "description": null,
                            "registrationState": "close"
                          },
                          {
                            "courseID": 23,
                            "title": "🔔 مجاني 🔖 توجد شهادة حضور 📢 Sleep & Circadian Rhythms During COVID19",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200923102728.jpeg",
                            "coverH": 198,
                            "coverW": 214,
                            "publishDate": "2020-09-23 10:43:01",
                            "publisheWrit": "قبل شهر",
                            "viewCount": 18,
                            "description": null,
                            "registrationState": "close"
                          },
                          {
                            "courseID": 13,
                            "title": "تجربة",
                            "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200831151429.jpeg",
                            "coverH": 750,
                            "coverW": 750,
                            "publishDate": "2020-09-17 13:11:48",
                            "publisheWrit": "قبل شهر",
                            "viewCount": 13,
                            "description": "تجربة تجربة",
                            "registrationState": "close"
                          }
                        ],
                        "first_page_url": "http://ertiqa.svod.app/api/courses/all?page=1",
                        "from": 1,
                        "last_page": 2,
                        "last_page_url": "http://ertiqa.svod.app/api/courses/all?page=2",
                        "next_page_url": "http://ertiqa.svod.app/api/courses/all?page=2",
                        "path": "http://ertiqa.svod.app/api/courses/all",
                        "per_page": 10,
                        "prev_page_url": null,
                        "to": 10,
                        "total": 15
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "API"
        ],
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "itemsPerPage": {
                    "type": "integer"
                  },
                  "cityID": {
                    "type": "string"
                  },
                  "specialtiesID": {
                    "type": "string"
                  },
                  "registerationState": {
                    "type": "string"
                  },
                  "startDate": {
                    "type": "string",
                    "format": "date"
                  },
                  "endDate": {
                    "type": "string",
                    "format": "date"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/show/{courseID}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "courseID",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Show Course",
        "tags": [
          "API"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Example": {
                    "value": {
                      "status": "Action Completed",
                      "message": "تم جلب بيانات الدورة التدريبية",
                      "data": {
                        "id": 2,
                        "title": "Clinical Toxicology Course",
                        "description": null,
                        "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200804143512.jpeg",
                        "companyName": "www.deeplearn360.com",
                        "companyID": 3,
                        "startDate": "2020-08-09",
                        "hijriDate": "1441-12-19",
                        "endDate": null,
                        "daysCount": 3,
                        "hoursCount": 0,
                        "registerStart": "2020-08-09",
                        "registerEnd": "2020-08-11",
                        "registrationLink": "deeplearn360.com/august",
                        "accrediting": [
                          "CME"
                        ],
                        "price": 350,
                        "priceConditions": [
                          {
                            "price": "350",
                            "currency": "ريال سعودي",
                            "condition": "السعر العام "
                          }
                        ],
                        "limitPositions": 0,
                        "details": null,
                        "userID": 6,
                        "user": "Essam",
                        "stateID": "published",
                        "places": [
                          {
                            "placeID": 1,
                            "placeName": "أون لاين",
                            "cityID": "online",
                            "cityName": "أون لاين",
                            "startDate": "2020-08-09",
                            "endDate": "2020-08-11",
                            "startTime": "16:00:00",
                            "endTime": "18:00:00",
                            "locationLink": "https://",
                            "description": null,
                            "locationDetails": "http://"
                          }
                        ],
                        "attachments": [
                          {
                            "id": 5,
                            "name": "صورة الإعلان",
                            "description": "null",
                            "fileType": "jpeg",
                            "path": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200804144423.jpeg"
                          }
                        ],
                        "specialties": [
                          {
                            "specialtiesID": 1,
                            "name": "جميع الممارسين الصحيين"
                          }
                        ],
                        "communications": [
                          {
                            "id": 13,
                            "name": "الموقع الإلكتروني",
                            "logo": "https://img.icons8.com/offices/80/000000/internet.png",
                            "value": "http://www.deeplearn360.com",
                            "note": "null",
                            "linkInitial": "http://"
                          }
                        ],
                        "created_at": "2020-08-04",
                        "published_date": "2020-08-10 17:48:38",
                        "publisheWrit": "قبل شهرين",
                        "viewCount": 13
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Example": {
                    "value": {
                      "status": "Unkown State",
                      "message": "غير مصرح لك عرض الدورة التدريبية",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-show-courseID",
        "description": "",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization"
          }
        ]
      }
    },
    "/home": {
      "get": {
        "summary": "Get Home Courses",
        "tags": [
          "API"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example": {
                    "value": {
                      "status": "Action Completed",
                      "message": "تم جلب ال الدورات التدريبية",
                      "data": [
                        {
                          "courseID": 43,
                          "title": "📢الدورة التاسعة لورشة عمل مراجعة الأمراض المعدية لدى الأطفال",
                          "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20201021210914.jpeg",
                          "coverH": 1280,
                          "coverW": 906,
                          "publishDate": "2020-10-21 21:54:30",
                          "publisheWrit": "اليوم",
                          "viewCount": 0,
                          "description": null,
                          "registrationState": "Open"
                        },
                        {
                          "courseID": 33,
                          "title": "عنوان الدورة التدريبة",
                          "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200929193120.jpeg",
                          "coverH": 750,
                          "coverW": 750,
                          "publishDate": "2020-09-29 19:32:22",
                          "publisheWrit": "خلال هذا الشهر",
                          "viewCount": 71,
                          "description": null,
                          "registrationState": "close"
                        },
                        {
                          "courseID": 28,
                          "title": "دورة تشخيص و علاج مشاكل مفصل القدم",
                          "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200925060922.jpeg",
                          "coverH": 1280,
                          "coverW": 839,
                          "publishDate": "2020-09-25 07:00:56",
                          "publisheWrit": "خلال هذا الشهر",
                          "viewCount": 79,
                          "description": null,
                          "registrationState": "not Open"
                        },
                        {
                          "courseID": 22,
                          "title": "ملتقى متطوع بعلمي",
                          "coverPic": "http://ertiqa.svod.app/storage/sectionsFiles/f_20200921170711.jpeg",
                          "coverH": 198,
                          "coverW": 214,
                          "publishDate": "2020-09-24 18:53:35",
                          "publisheWrit": "خلال هذا الشهر",
                          "viewCount": 15,
                          "description": null,
                          "registrationState": "close"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-home",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Authorization"
          }
        ],
        "description": "Will return 4 courses for home page"
      }
    }
  },
  "components": {
    "schemas": {}
  },
  "tags": [
    {
      "name": "API"
    }
  ]
}